# Generated by Django 5.2 on 2025-05-05 00:23

from django.db import migrations
import random

def get_random_recipients(sender_id, num_recipients):
    possible_recipients = list(range(1, 7))
    possible_recipients.remove(sender_id)
    return random.sample(possible_recipients, num_recipients)

def add_data(apps, schema_editor):
    Email = apps.get_model('mail', 'Email')

    subjects = [
        "Meeting Reminder", "Project Update", "Quick Question",
        "Lunch Plans", "Weekend Getaway Ideas", "Document Review Request",
        "Invoice Attached", "Welcome!", "Following Up", "Vacation Request",
        "Team Sync Next Week", "Feedback Request", "Important Announcement",
        "New Policy Update", "Training Session Reminder", "Happy Birthday!",
        "System Maintenance Notice", "Weekly Newsletter", "Event Invitation",
        "Survey Participation Request", "Congratulations!", "Password Reset",
        "Account Verification", "Service Downtime Alert", "Thank You Note",
        "Performance Review", "Holiday Greetings", "Team Outing Details",
        "Budget Approval Request", "Customer Testimonial Request"
    ]

    bodies = [
        "Just a friendly reminder about our meeting tomorrow at 10 AM. Please make sure to review the agenda beforehand and come prepared with any updates or questions you might have. This meeting is crucial for aligning our goals and ensuring everyone is on the same page. Let me know if you have any conflicts or need to reschedule.",
        "Here's the latest update on the project status. The team has been working diligently to meet the deadlines, and we have made significant progress in the past week. However, there are still a few challenges that need to be addressed, particularly in the testing phase. I have attached a detailed report for your review. Please let me know your thoughts and if there are any adjustments needed to the current plan.",
        "Do you have a moment to discuss the latest client feedback? The client has provided some valuable insights that could help us improve our approach and deliver better results. I believe it is important to address their concerns promptly to maintain a strong relationship. Let me know when you are available for a quick call or meeting to go over the details.",
        "Are you free for lunch sometime next week? It would be great to catch up and discuss some ideas I have been working on. I think your input would be incredibly valuable, and it would also be a good opportunity to brainstorm together. Let me know your availability, and I can make the necessary arrangements.",
        "Thinking about a trip next month. Any suggestions? I am looking for a destination that offers a mix of relaxation and adventure. If you have any recommendations based on your past experiences, I would love to hear them. Also, if you are interested in joining, let me know, and we can plan something together.",
        "Could you please review the attached document when you have a chance? It contains the latest updates and proposed changes to the project. Your feedback is crucial to ensure we are heading in the right direction. If you have any questions or need further clarification, feel free to reach out to me directly.",
        "Please find the invoice for the recent services attached. If you have any questions or concerns regarding the charges, do not hesitate to contact me. We appreciate your prompt payment to ensure the continuity of our services. Thank you for your business and support.",
        "Welcome to the team! We're excited to have you. As you settle in, please feel free to reach out if you have any questions or need assistance. We are here to support you and ensure your transition is as smooth as possible. Looking forward to working together and achieving great things.",
        "Just following up on my previous email regarding the proposal. I wanted to ensure you had a chance to review it and provide your feedback. Your input is essential to finalize the details and move forward. Please let me know if you need any additional information or have any concerns.",
        "I'd like to request vacation time from June 10th to June 14th. During this period, I will ensure all my responsibilities are delegated and any pending tasks are completed beforehand. Please let me know if this works for the team or if there are any conflicts that need to be addressed.",
        "The team sync is scheduled for next week. Please mark your calendars and prepare any updates or questions you may have. This is a great opportunity to align our efforts and ensure we are all moving in the same direction.",
        "I would appreciate your feedback on the attached document. Your insights are invaluable, and I want to ensure we are considering all perspectives before finalizing the plan.",
        "We have an important announcement to share with the team. Please make sure to attend the meeting tomorrow at 3 PM. This will be a great opportunity to discuss the changes and address any questions.",
        "The new policy update has been released. Please review the attached document and let me know if you have any questions or concerns. Your understanding and compliance are greatly appreciated.",
        "This is a reminder about the upcoming training session. Please make sure to register and complete any pre-session requirements. This training is essential for your professional development.",
        "Happy Birthday! Wishing you a fantastic day filled with joy and celebration. Thank you for being an amazing part of our team.",
        "We will be performing system maintenance this weekend. Please ensure you save your work and log out of the system before the scheduled downtime. Thank you for your cooperation.",
        "Here is this week's newsletter. It contains important updates and announcements. Please take a moment to review it and let me know if you have any questions.",
        "You are invited to our upcoming event. Please RSVP by the end of the week to confirm your attendance. We look forward to seeing you there!",
        "We would greatly appreciate your participation in our survey. Your feedback is crucial to help us improve and serve you better. Thank you for your time and input.",
        "Congratulations on your recent achievement! Your hard work and dedication have truly paid off. We are proud to have you on our team.",
        "If you need to reset your password, please follow the instructions in this email. If you did not request a password reset, please contact support immediately.",
        "Please verify your account by clicking the link below. This step is necessary to ensure the security of your account and access to our services.",
        "We are experiencing a temporary service downtime. Our team is working diligently to resolve the issue. Thank you for your patience and understanding.",
        "Thank you for your recent contribution. Your efforts have made a significant impact, and we truly appreciate your dedication and hard work.",
        "Your performance review is scheduled for next week. Please prepare any questions or topics you would like to discuss. This is a great opportunity to reflect on your achievements and set goals for the future.",
        "Wishing you and your loved ones a wonderful holiday season. May this time be filled with joy, peace, and happiness.",
        "We are planning a team outing next month. Please let us know your availability and any suggestions you may have. This will be a great opportunity to bond and have some fun together.",
        "We need your approval for the proposed budget. Please review the attached document and provide your feedback at your earliest convenience.",
        "We would love to feature your testimonial on our website. If you are willing to share your experience, please let us know. Your feedback is invaluable to us."
    ]

    for i in range(30):
        sender_id = random.randint(1, 6)
        recipients = get_random_recipients(sender_id, random.randint(1, 3))
        subject = subjects[i]
        body = bodies[i]

        email = Email.objects.create(
            user_id=sender_id,
            sender_id=sender_id,
            subject=subject,
            body=body,
            read=True,
            archived=False
        )
        email.recipients.set(recipients)

        for recipient_id in recipients:
            Email.objects.create(
                user_id=recipient_id,
                sender_id=sender_id,
                subject=subject,
                body=body,
                read=random.choice([True, False]),
                archived=False
            ).recipients.set(recipients)


def remove_data(apps, schema_editor):
    Email = apps.get_model('mail', 'Email')
    Email.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_add_users'),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
