# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations


def add_data(apps, schema_editor):
    categories = apps.get_model('auctions', 'Category')
    categories.objects.create(name='Electronics')
    categories.objects.create(name='Board Games')
    categories.objects.create(name='Household')
    categories.objects.create(name='Outdoor')


def remove_data(apps, schema_editor):
    categories = apps.get_model('auctions', 'Category')
    categories.objects.filter(name='Electronics').delete()
    categories.objects.filter(name='Board Games').delete()
    categories.objects.filter(name='Household').delete()
    categories.objects.filter(name='Outdoor').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auction_bid_category_comment_watchlist"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
