# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_data(apps, schema_editor):
    categories = apps.get_model('auctions', 'Category')
    categories.objects.create(name='Electronics')
    categories.objects.create(name='Toys')
    categories.objects.create(name='Household')
    categories.objects.create(name='Outdoor')
    categories.objects.create(name='Sports')

    users = apps.get_model('auctions', 'User')
    users.objects.create(username='admin', password=make_password('admin'), email='admin@example.com', first_name='admin', last_name='admin', is_superuser=True, is_staff=True)
    users.objects.create(username='mike', password=make_password('mike'), email='mike@example.com', first_name='mike', last_name='jones', is_superuser=True, is_staff=True)
    users.objects.create(username='bob', password=make_password('bob'), email='bob@example.com', first_name='bob', last_name='carter', is_superuser=False)
    users.objects.create(username='emma', password=make_password('emma'), email='emma@example.com', first_name='emma', last_name='wilson', is_superuser=False)
    users.objects.create(username='james', password=make_password('james'), email='james@example.com', first_name='james', last_name='harris', is_superuser=False)
    users.objects.create(username='sally', password=make_password('sally'), email='sally@example.com', first_name='sally', last_name='mitchell', is_superuser=False)

def remove_data(apps, schema_editor):
    categories = apps.get_model('auctions', 'Category')
    categories.objects.filter(name='Electronics').delete()
    categories.objects.filter(name='Toys').delete()
    categories.objects.filter(name='Household').delete()
    categories.objects.filter(name='Outdoor').delete()
    categories.objects.filter(name='Sports').delete()

    users = apps.get_model('auctions', 'User')
    users.objects.filter(username='admin').delete()
    users.objects.filter(username='mike').delete()
    users.objects.filter(username='bob').delete()
    users.objects.filter(username='emma').delete()
    users.objects.filter(username='james').delete()
    users.objects.filter(username='sally').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auction_bid_category_comment_watchlist"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
