# Generated by Django 5.2 on 2025-04-15 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_add_initial_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="auctions",
        ),
        migrations.AddField(
            model_name="auction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auctions",
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
