# Generated by Django 5.2 on 2025-04-17 04:05

from django.db import migrations


image_url = {
    "Playstation 5": "https://m.media-amazon.com/images/I/51CXJ8Rl7UL._AC_SL1500_.jpg",
    "Xbox Series X": "https://m.media-amazon.com/images/I/515tLyCgdXL._AC_SL1080_.jpg",
    "Nintendo Switch": "https://m.media-amazon.com/images/I/71wpE+ZIehL._SL1500_.jpg",
    "MacBook Pro": "https://m.media-amazon.com/images/I/71u7ZoxwLkL._AC_SL1500_.jpg",
    "Dell XPS 13": "https://m.media-amazon.com/images/I/710EGJBdIML._AC_SL1500_.jpg",
    "Star Wars Lego": "https://m.media-amazon.com/images/I/81qXFDqm5VL._AC_SL1500_.jpg",
    "Barbie Dreamhouse": "https://m.media-amazon.com/images/I/81of-jU8o3L._AC_SL1500_.jpg",
    "Hot Wheels Track Set": "https://m.media-amazon.com/images/I/71XBXLToIyL._AC_SL1500_.jpg",
    "Nerf Rival Blaster": "https://m.media-amazon.com/images/I/718c6X88MjL._AC_SL1500_.jpg",
    "Monopoly Deluxe Edition": "https://m.media-amazon.com/images/I/81hKuIqGP2L._AC_SL1336_.jpg",
    "Minecraft LEGO Set": "https://m.media-amazon.com/images/I/81tvXj2z3XL._AC_SL1500_.jpg",
    "Uno Giant Edition": "https://m.media-amazon.com/images/I/81-Sdo9Sa9L._AC_SL1500_.jpg",
    "Dyson V15 Vacuum": "https://m.media-amazon.com/images/I/613doEjslUL._AC_SL1500_.jpg",
    "Keurig Coffee Maker": "https://m.media-amazon.com/images/I/61hZIUf9iDL._AC_SL1500_.jpg",
    "Instant Pot Duo": "https://m.media-amazon.com/images/I/71rFttpTtlL._AC_SL1500_.jpg",
    "Ninja Air Fryer": "https://m.media-amazon.com/images/I/71QwoGmcfUL._AC_SL1500_.jpg",
    "Roomba i7 Robot Vacuum": "https://m.media-amazon.com/images/I/61HDNUCNh9L._AC_SL1500_.jpg",
    "Brita Water Pitcher": "https://m.media-amazon.com/images/I/71cOMoKvH0L._AC_SL1500_.jpg",
    "Bamboo Cutting Board": "https://m.media-amazon.com/images/I/71Z42o3YqnL._AC_SL1500_.jpg",
    "Ironing Board": "https://m.media-amazon.com/images/I/61Z5fG20AnL._AC_SL1500_.jpg",
    "Weber Charcoal Grill": "https://m.media-amazon.com/images/I/71uQnSUmBFL._AC_SL1500_.jpg",
    "Coleman Camping Stove": "https://m.media-amazon.com/images/I/61b-Kz+go7L._AC_SL1500_.jpg",
    "Yeti Cooler": "https://m.media-amazon.com/images/I/61csSsffOhL._AC_SL1500_.jpg",
    "Folding Camping Chairs": "https://m.media-amazon.com/images/I/71v8Qm4qN+L._AC_SL1500_.jpg",
    "Hammock with Stand": "https://m.media-amazon.com/images/I/81UQ1W1qiPL._AC_SL1500_.jpg",
    "Garden Hose Reel": "https://m.media-amazon.com/images/I/71qngyqEVHL._AC_SL1500_.jpg",
    "Rawlings Baseball Bat": "https://m.media-amazon.com/images/I/71MlXgOA9zL._AC_SL1500_.jpg",
    "Nike Soccer Ball": "https://m.media-amazon.com/images/I/71hpcjKJ9tL._AC_SL1400_.jpg",
    "Basketball Hoop Set": "https://m.media-amazon.com/images/I/81fJGHZhG5L._AC_SL1500_.jpg",
    "Trek Mountain Bike": "https://m.media-amazon.com/images/I/71PyGlehAFL._AC_SL1500_.jpg",
    "Yoga Mat Set": "https://m.media-amazon.com/images/I/71U3oP3IqsL._AC_SL1500_.jpg",
    "Adjustable Dumbbells": "https://m.media-amazon.com/images/I/61jaTm1zksL._AC_SL1433_.jpg",
    "Ping Pong Table": "https://m.media-amazon.com/images/I/71Z1Tb1dboL._AC_SL1500_.jpg",
    "Skateboard Helmet": "https://m.media-amazon.com/images/I/61XcEyjtUBL._AC_SL1500_.jpg",
    "Tennis Racket Pair": "https://m.media-amazon.com/images/I/71avHPyv7pL._AC_SL1500_.jpg",
    "Golf Club Starter Set": "https://m.media-amazon.com/images/I/71nbhPf+6gL._AC_SL1500_.jpg"
}


def add_data(apps, schema_editor):
    categories = apps.get_model('auctions', 'Category')
    users = apps.get_model('auctions', 'User')
    auctions = apps.get_model('auctions', 'Auction')
    auctions.objects.create(title='Playstation 5', description='desc', start_bid='100', is_active=True, owner=users.objects.get(username='mike'), category=categories.objects.get(name='Electronics'))
    auctions.objects.create(
        title='Playstation 5',
        description='This is a lightly used Playstation 5 that’s in fantastic condition. It has been carefully maintained in a clean, smoke-free home. I’ve had it for about eight months, but due to a busy schedule, it hasn’t seen much use. The console includes one original DualSense controller, power cable, HDMI cable, and the original box. The system has been factory reset and is ready for a new user. I’m also including a couple of popular digital titles already installed like Spider-Man: Miles Morales and God of War: Ragnarok, which are perfect for showcasing the PS5’s graphics and speed. Everything works flawlessly—the fan is quiet, no overheating, and the controller is in great shape. This is an excellent chance to get a high-demand console at a good price without having to wait for a restock. I’ll make sure it’s shipped securely and safely. Reach out with any questions!',
        image_url=image_url['Playstation 5'],
        start_bid=350,
        is_active=True,
        owner=users.objects.get(username='bob'),
        category=categories.objects.get(name='Electronics')
    )

    auctions.objects.create(
        title='Xbox Series X',
        description='Up for auction is an Xbox Series X in excellent condition. This unit has been used moderately and has always been kept in a well-ventilated entertainment center. I’m including the original wireless controller, HDMI cable, power cord, and box. It’s been factory reset and updated to the latest software version. I’m also throwing in three digital games: Halo Infinite, Forza Horizon 5, and Call of Duty: Modern Warfare II. This console is a beast—it runs games with ultra-fast load times and crisp 4K visuals. Whether you’re a serious gamer or just upgrading from a previous-gen system, this Xbox Series X delivers. Everything works as expected, and there are no scratches, dents, or performance issues. Selling only because I’ve switched over to PC gaming and want this console to go to someone who’ll enjoy it. I’ll make sure to ship it with care, and I’m happy to answer any questions!',
        image_url=image_url['Xbox Series X'],
        start_bid=300,
        is_active=True,
        owner=users.objects.get(username='emma'),
        category=categories.objects.get(name='Electronics')
    )

    auctions.objects.create(
        title='Nintendo Switch',
        description='This is a standard edition Nintendo Switch in great condition. It comes with the original red and blue Joy-Cons, dock, HDMI cable, power adapter, and original packaging. It’s been lightly used and shows minimal wear. The screen is scratch-free and has had a protector on since day one. I’m including two games: Mario Kart 8 Deluxe and The Legend of Zelda: Breath of the Wild—two of the best titles the Switch has to offer. The Joy-Cons work perfectly with no drift, and the battery still holds a solid charge. Great for handheld play on the go or docked for big-screen action. Selling because I’ve recently upgraded to the OLED version. This is an ideal system for families, casual gamers, or anyone wanting a fun and portable console experience. I’ll pack it securely for shipping and dispatch it quickly. Let me know if you’d like photos or more info!',
        image_url=image_url['Nintendo Switch'],
        start_bid=200,
        is_active=True,
        owner=users.objects.get(username='mike'),
        category=categories.objects.get(name='Electronics')
    )

    auctions.objects.create(
        title='MacBook Pro',
        description='Selling my MacBook Pro (13-inch, 2020 model) with Apple’s M1 chip, 8GB RAM, and 256GB SSD. It’s in excellent cosmetic and functional condition, with no scratches on the screen or body. Used mainly for schoolwork and some light coding projects. The battery cycle count is low, and it still holds a full day’s charge. Comes with the original charger and box. The keyboard is clean and responsive, and the Retina display is vibrant and crisp. This is a great laptop for students, creatives, or professionals who need speed, reliability, and great battery life. I’m switching to a larger screen for video editing, which is the only reason I’m parting with it. I’ve wiped it clean and reinstalled macOS, so it’s ready for a fresh start. You won’t find a better MacBook at this price point in such good condition. Fast shipping and secure packaging guaranteed!',
        image_url=image_url['MacBook Pro'],
        start_bid=700,
        is_active=True,
        owner=users.objects.get(username='sally'),
        category=categories.objects.get(name='Electronics')
    )

    auctions.objects.create(
        title='Dell XPS 13',
        description='This is a Dell XPS 13 (2021 model) with an 11th Gen Intel i7 processor, 16GB RAM, and 512GB SSD. It’s a beautiful, ultra-portable laptop with a near-borderless display that’s perfect for working on the go. The condition is like new—no dents, scratches, or issues. I’ve only used it for light tasks like web browsing and document editing. The battery lasts 8–10 hours with ease, and the performance is snappy. Comes with the original charger and box. I’m moving to a desktop setup, so I no longer need this laptop. It’s been factory reset and updated to the latest version of Windows. This is ideal for professionals, students, or anyone wanting a premium Windows laptop. The keyboard and touchpad feel excellent, and the screen is bright and color accurate. Will ship carefully packed with tracking included. Let me know if you want more details or pictures!',
        image_url=image_url['Dell XPS 13'],
        start_bid=600,
        is_active=True,
        owner=users.objects.get(username='james'),
        category=categories.objects.get(name='Electronics')
    )

    auctions.objects.create(
        title='Star Wars Lego',
        description='This is a complete Star Wars LEGO set featuring the Millennium Falcon. It’s been carefully assembled once and then stored on a shelf away from dust and sunlight. All original pieces are included, along with the instruction manual and the box in good condition. The set includes detailed mini-figures of Han Solo, Chewbacca, Princess Leia, and others. It’s an ideal item for collectors or LEGO enthusiasts looking for a centerpiece model. There are no missing or damaged bricks, and I’ve kept everything sorted and organized. Selling to make room for newer sets in my growing collection. Whether you want to rebuild it yourself or display it as-is, this set delivers both fun and nostalgia. Shipping will be secure and prompt. Let me know if you want more pictures!',
        image_url=image_url['Star Wars Lego'],
        start_bid=90,
        is_active=True,
        owner=users.objects.get(username='emma'),
        category=categories.objects.get(name='Toys')
    )

    auctions.objects.create(
        title='Barbie Dreamhouse',
        description='This Barbie Dreamhouse is in fantastic condition and comes fully assembled. It includes most of the original furniture and accessories, such as a working elevator, lights, and sounds in the kitchen and bathroom, and even a puppy play area. My daughter has outgrown it, so we’re passing it on. Everything functions perfectly, and it’s been kept indoors in a clean, smoke-free home. There are minor signs of play but nothing broken or missing that affects usability. Perfect for any Barbie fan or imaginative child who loves setting up detailed dollhouse scenes. The house will be partially disassembled for easier shipping and comes with instructions for quick reassembly. Feel free to ask any questions!',
        image_url=image_url['Barbie Dreamhouse'],
        start_bid=75,
        is_active=True,
        owner=users.objects.get(username='mike'),
        category=categories.objects.get(name='Toys')
    )

    auctions.objects.create(
        title='Hot Wheels Track Set',
        description='Selling a large Hot Wheels Track Builder set that includes dozens of track pieces, ramps, loops, and connectors. It’s a mix of sets combined into one awesome configuration. My kids had a blast creating mega tracks and racing cars, but they’ve since moved on to other interests. Everything is in working condition and includes several cars to get you started. A few pieces show light wear but nothing broken. This is ideal for creative kids who like designing wild race tracks. It comes in a plastic storage bin for easy organization. Great way to start or expand a Hot Wheels collection. Will ship securely!',
        image_url=image_url['Hot Wheels Track Set'],
        start_bid=40,
        is_active=True,
        owner=users.objects.get(username='sally'),
        category=categories.objects.get(name='Toys')
    )

    auctions.objects.create(
        title='Nerf Rival Blaster',
        description='Here’s a Nerf Rival Blaster (Prometheus MXVIII-20K model) in excellent working condition. This blaster is battery powered and fires at high velocity, making it one of the most powerful Nerf guns on the market. Includes the rechargeable battery pack, charger, and a full set of high-impact foam rounds. Only used a few times during indoor Nerf battles and always stored properly afterward. It’s perfect for competitive players or teens who want an edge in their next Nerf war. There are no cracks or jams, and the battery still holds a strong charge. Selling because we’re downsizing and clearing out gear. Will be packaged securely and shipped fast.',
        image_url=image_url['Nerf Rival Blaster'],
        start_bid=60,
        is_active=True,
        owner=users.objects.get(username='bob'),
        category=categories.objects.get(name='Toys')
    )

    auctions.objects.create(
        title='Monopoly Deluxe Edition',
        description='Monopoly Deluxe Edition board game in near-new condition. Comes in a beautiful wooden box with gold foil details and a felt-lined interior. All game pieces, money, cards, and property titles are included and organized. The game was only played a couple of times during family holidays, so everything is clean and damage-free. This is a great version of a classic game—ideal as a gift or for family game nights. The wooden houses and hotels give it a premium feel, and the board folds neatly for easy storage. Selling as we already have multiple versions of Monopoly. I’ll ship with care!',
        image_url=image_url['Monopoly Deluxe Edition'],
        start_bid=30,
        is_active=True,
        owner=users.objects.get(username='james'),
        category=categories.objects.get(name='Toys')
    )

    auctions.objects.create(
        title='Minecraft LEGO Set',
        description='This Minecraft LEGO set (The Creeper Mine 21155) is complete and in excellent condition. Built once and then displayed on a shelf. Includes all minifigures, accessories, and the original box and instructions. Perfect for Minecraft fans who enjoy constructing detailed, game-accurate builds. The model includes functional features like a minecart track and TNT launch. No missing or broken pieces, and everything is clean and well-sorted. Selling to make space for newer sets. A fun build and a great collector’s item!',
        image_url=image_url['Minecraft LEGO Set'],
        start_bid=50,
        is_active=True,
        owner=users.objects.get(username='emma'),
        category=categories.objects.get(name='Toys')
    )

    auctions.objects.create(
        title='Uno Giant Edition',
        description='This is a complete set of Uno Giant Edition with extra-large cards—great for parties, family gatherings, or outdoor play. The cards are durable and easy to read, making them especially fun for kids and seniors. Used only a few times during a backyard party, so they are clean and in excellent shape. Comes in original packaging with all cards present. A fun twist on a classic game! Selling because we have two sets. I’ll pack it securely for shipping and get it sent out quickly.',
        image_url=image_url['Uno Giant Edition'],
        start_bid=15,
        is_active=True,
        owner=users.objects.get(username='sally'),
        category=categories.objects.get(name='Toys')
    )

    auctions.objects.create(
        title='Dyson V15 Vacuum',
        description='Selling a Dyson V15 Detect cordless vacuum in excellent working condition. This is one of Dyson’s most powerful models and comes with the laser dust detection feature. I’ve used it lightly for about six months, mostly on hardwood floors, and it’s performed beautifully. Battery life is still strong, and all attachments are included: the high-torque cleaner head, laser slim fluffy head, and multiple nozzles. It’s been cleaned and sanitized thoroughly before listing. There are some minor cosmetic scuffs on the tube from regular use, but nothing that affects function. If you’re looking for a top-of-the-line cleaning tool, this is a great option at a fraction of the retail price. Will ship in its original box with manual.',
        image_url=image_url['Dyson V15 Vacuum'],
        start_bid=250,
        is_active=True,
        owner=users.objects.get(username='james'),
        category=categories.objects.get(name='Household')
    )

    auctions.objects.create(
        title='Keurig Coffee Maker',
        description='This Keurig K-Supreme Plus coffee maker is in near-new condition. It was used in a guest room for a few months and still brews perfectly. Comes with the original water reservoir, drip tray, and a reusable K-Cup filter. There are no cracks or damage, and it has been thoroughly cleaned and descaled. Ideal for anyone who enjoys quick, convenient coffee in the morning. This model supports multiple brew sizes and has a customizable strength setting. The stainless steel finish looks great on any kitchen counter. Selling because we’ve switched to a different coffee system. Ships safely packed with all parts.',
        image_url=image_url['Keurig Coffee Maker'],
        start_bid=65,
        is_active=True,
        owner=users.objects.get(username='mike'),
        category=categories.objects.get(name='Household')
    )

    auctions.objects.create(
        title='Instant Pot Duo',
        description='Up for auction is a 6-quart Instant Pot Duo that’s been gently used and is in excellent shape. It’s perfect for quick weeknight meals and batch cooking. Includes the stainless steel inner pot, steam rack, and original lid with sealing ring. No odors, dents, or mechanical issues. We’re only selling it because we received a larger model as a gift. This Instant Pot has 7 cooking functions including pressure cooking, sautéing, slow cooking, and yogurt making. It’s ideal for busy families or meal preppers. Includes printed instruction manual and recipes. A fantastic kitchen tool ready for a new home!',
        image_url=image_url['Instant Pot Duo'],
        start_bid=50,
        is_active=True,
        owner=users.objects.get(username='bob'),
        category=categories.objects.get(name='Household')
    )

    auctions.objects.create(
        title='Ninja Air Fryer',
        description='Selling a 4-quart Ninja Air Fryer in excellent condition. It’s been used sparingly and cleaned after every use. Cooks crisp and healthy meals with little to no oil. Includes original basket and crisper plate, all cleaned and ready to go. Digital controls work perfectly, and the non-stick coating is intact. A great tool for quick dinners, snacks, or reheating leftovers. We’ve simply upgraded to a dual-basket model. This air fryer is compact, efficient, and perfect for smaller households or first-time users. I’ll pack it safely and ship fast.',
        image_url=image_url['Ninja Air Fryer'],
        start_bid=45,
        is_active=True,
        owner=users.objects.get(username='bob'),
        category=categories.objects.get(name='Household')
    )

    auctions.objects.create(
        title='Roomba i7 Robot Vacuum',
        description='Roomba i7 robotic vacuum for sale, lightly used and in great condition. It maps your home and vacuums smartly in straight lines. Includes the charging dock, original filter, and two virtual wall barriers. Great for homes with pets—does a great job picking up hair and crumbs. The vacuum has been fully cleaned and reset. Battery holds a solid charge and navigation works perfectly. I’m only selling because we’ve switched to a newer model with mop capability. A great value for anyone looking to automate their home cleaning. Ships in original box.',
        image_url=image_url['Roomba i7 Robot Vacuum'],
        start_bid=180,
        is_active=True,
        owner=users.objects.get(username='james'),
        category=categories.objects.get(name='Household')
    )

    auctions.objects.create(
        title='Brita Water Pitcher',
        description='This is a Brita Longlast+ water filter pitcher with a 10-cup capacity. Gently used, thoroughly cleaned, and includes one new filter. The lid and handle are in perfect condition, and it pours without leaks. Ideal for home or office use, especially if you’re trying to cut down on bottled water. Fits easily in most refrigerator doors. We’ve moved to a countertop system and no longer need this one. A good, sustainable choice for anyone wanting clean-tasting water every day. Ships clean and ready to use.',
        image_url=image_url['Brita Water Pitcher'],
        start_bid=15,
        is_active=True,
        owner=users.objects.get(username='james'),
        category=categories.objects.get(name='Household')
    )

    auctions.objects.create(
        title='Bamboo Cutting Board',
        description='Up for grabs is a large bamboo cutting board with juice groove. Used only a few times for serving, not heavy chopping. It’s naturally antibacterial and easy to clean. There are light surface marks from use, but no warping, cracks, or major wear. Perfect for prepping vegetables or serving charcuterie. Selling as we’re minimizing kitchen items. It’s been oiled recently and well cared for. A great addition to any kitchen.',
        image_url=image_url['Bamboo Cutting Board'],
        start_bid=20,
        is_active=True,
        owner=users.objects.get(username='sally'),
        category=categories.objects.get(name='Household')
    )

    auctions.objects.create(
        title='Ironing Board',
        description='Standard size ironing board with adjustable height and sturdy frame. Comes with a padded cotton cover in a neutral gray pattern. It’s in good condition with minor cosmetic wear but very stable during use. Folds flat for easy storage. Ideal for everyday use or small apartments. Selling because we’ve switched to a garment steamer. Clean and ready to go!',
        image_url=image_url['Ironing Board'],
        start_bid=25,
        is_active=True,
        owner=users.objects.get(username='mike'),
        category=categories.objects.get(name='Household')
    )

    auctions.objects.create(
        title='Weber Charcoal Grill',
        description='Classic Weber 22-inch kettle charcoal grill in very good condition. Used only a few times during summer, always covered. Includes built-in thermometer, ash catcher, and hinged cooking grate. No rust or dents. Produces excellent heat for grilling burgers, steaks, or smoking ribs. Comes with the original manual. Selling as we’ve upgraded to a larger model for family events. Easy to clean and transport. Great for backyard BBQs!',
        image_url=image_url['Weber Charcoal Grill'],
        start_bid=75,
        is_active=True,
        owner=users.objects.get(username='emma'),
        category=categories.objects.get(name='Outdoor')
    )

    auctions.objects.create(
        title='Coleman Camping Stove',
        description='Two-burner Coleman propane camping stove in working order. Includes wind shields and uses standard 16oz propane canisters. Ideal for car camping or backyard cooking. Used on two weekend trips. Clean, with all parts functioning smoothly. Lightweight and compact when folded. Selling because we’re switching to a single-burner backpacking stove. Reliable and easy to use. Ships quickly!',
        image_url=image_url['Coleman Camping Stove'],
        start_bid=40,
        is_active=True,
        owner=users.objects.get(username='bob'),
        category=categories.objects.get(name='Outdoor')
    )

    auctions.objects.create(
        title='Yeti Cooler',
        description='Selling a Yeti Tundra 45 cooler in tan. Holds ice for days—ideal for camping, tailgates, or beach trips. Used for one summer and kept clean. There are minor scuffs on the exterior but no cracks or leaks. Rubber latches and handles work perfectly. Holds up to 26 cans with recommended ice. We’re moving and downsizing gear. Fantastic cooler that lives up to its reputation!',
        image_url=image_url['Yeti Cooler'],
        start_bid=180,
        is_active=True,
        owner=users.objects.get(username='emma'),
        category=categories.objects.get(name='Outdoor')
    )

    auctions.objects.create(
        title='Folding Camping Chairs',
        description='Pair of folding camping chairs with cup holders and carrying bags. Used for two camping trips, still in great shape. No rips, mold, or broken parts. Comfortable and lightweight—perfect for outdoor concerts or weekend camping. Easy to set up and pack down. Selling as we’ve upgraded to padded recliner chairs. Clean and ready for use.',
        image_url=image_url['Folding Camping Chairs'],
        start_bid=25,
        is_active=True,
        owner=users.objects.get(username='sally'),
        category=categories.objects.get(name='Outdoor')
    )

    auctions.objects.create(
        title='Hammock with Stand',
        description='Double-size hammock with heavy-duty steel stand. Used for one season and stored indoors when not in use. Includes carrying case and cotton fabric sling in striped pattern. Very stable and comfortable. Great for relaxing in your backyard, patio, or while camping. Selling to free up space. Disassembles quickly for transport. Ready to enjoy!',
        image_url=image_url['Hammock with Stand'],
        start_bid=50,
        is_active=True,
        owner=users.objects.get(username='mike'),
        category=categories.objects.get(name='Outdoor')
    )

    auctions.objects.create(
        title='Garden Hose Reel',
        description='Wall-mount garden hose reel with 100-foot hose. Includes spray nozzle and mounting hardware. Hose is kink-resistant and reel works smoothly. Used a few times for watering plants. No leaks or damage. Selling because we’ve switched to a different irrigation system. Clean and ready to install.',
        image_url=image_url['Garden Hose Reel'],
        start_bid=30,
        is_active=True,
        owner=users.objects.get(username='sally'),
        category=categories.objects.get(name='Outdoor')
    )

    auctions.objects.create(
        title='Rawlings Baseball Bat',
        description='Rawlings Velo aluminum baseball bat, 32-inch, lightly used during one high school season. Bat is in good condition with minor scuffing from games. No dents or cracks. Has excellent pop and balance. Selling as my son has moved up to college-level gear. Great for practice or games. Grip still has life left. Ships safely.',
        image_url=image_url['Rawlings Baseball Bat'],
        start_bid=60,
        is_active=True,
        owner=users.objects.get(username='james'),
        category=categories.objects.get(name='Sports')
    )

    auctions.objects.create(
        title='Nike Soccer Ball',
        description='Official size 5 Nike Premier League soccer ball. Used for weekend play, still holds air well. No tears or major wear. Excellent grip and balance. Cleaned and ready to go. Selling because I received a newer model as a gift. Great for training or matches.',
        image_url=image_url['Nike Soccer Ball'],
        start_bid=20,
        is_active=True,
        owner=users.objects.get(username='bob'),
        category=categories.objects.get(name='Sports')
    )

    auctions.objects.create(
        title='Basketball Hoop Set',
        description='Portable basketball hoop with adjustable height. Includes base (fill with water or sand), clear backboard, and rim. Used in driveway for two seasons, still solid and functional. Some weathering on metal parts but nothing affecting play. Great for kids and teens. Selling due to moving. Can disassemble for transport.',
        image_url=image_url['Basketball Hoop Set'],
        start_bid=85,
        is_active=True,
        owner=users.objects.get(username='mike'),
        category=categories.objects.get(name='Sports')
    )

    auctions.objects.create(
        title='Trek Mountain Bike',
        description='Trek Marlin 5 mountain bike, medium frame, in excellent shape. 21-speed with front suspension. Used lightly on trails and mostly kept in garage. Tires and brakes in great condition. Selling because I upgraded to a full-suspension model. Great entry-level MTB for beginners or casual riders.',
        image_url=image_url['Trek Mountain Bike'],
        start_bid=300,
        is_active=True,
        owner=users.objects.get(username='sally'),
        category=categories.objects.get(name='Sports')
    )

    auctions.objects.create(
        title='Yoga Mat Set',
        description='Yoga mat set including extra-thick mat, two foam blocks, and a strap. Used a handful of times for home practice. Clean, non-slip, and still in like-new condition. Great for beginners or advanced users. Selling as I’ve joined a gym that provides mats. Stored rolled up in closet.',
        image_url=image_url['Yoga Mat Set'],
        start_bid=20,
        is_active=True,
        owner=users.objects.get(username='bob'),
        category=categories.objects.get(name='Sports')
    )

    auctions.objects.create(
        title='Adjustable Dumbbells',
        description='Pair of adjustable dumbbells ranging from 5 to 50 lbs each. Includes stand for easy storage. Used for a few months during lockdown workouts. In great condition with smooth selector dials. Selling due to gym membership. Great for compact home gyms. Will require local pickup due to weight.',
        image_url=image_url['Adjustable Dumbbells'],
        start_bid=120,
        is_active=True,
        owner=users.objects.get(username='mike'),
        category=categories.objects.get(name='Sports')
    )

    auctions.objects.create(
        title='Ping Pong Table',
        description='Full-size ping pong table with fold-up design and wheels for storage. Comes with net, paddles, and balls. Used sparingly in our basement rec room. No cracks or warping. Surface is smooth and bounces well. Selling due to space constraints. Great family fun or casual matches!',
        image_url=image_url['Ping Pong Table'],
        start_bid=150,
        is_active=True,
        owner=users.objects.get(username='sally'),
        category=categories.objects.get(name='Sports')
    )

    auctions.objects.create(
        title='Skateboard Helmet',
        description='Standard skateboard deck with grip tape and ABEC-7 bearings. Includes size M helmet. Used for about two months on smooth pavement. Wheels and trucks are in good shape. Minor scuffing on the board but no structural damage. Perfect starter board for a teen or casual rider.',
        image_url=image_url['Skateboard Helmet'],
        start_bid=45,
        is_active=True,
        owner=users.objects.get(username='bob'),
        category=categories.objects.get(name='Sports')
    )

    auctions.objects.create(
        title='Tennis Racket Pair',
        description='Pair of Wilson tennis rackets with covers. Both are adult size and lightly used. Strings and grips in good condition. Great for beginners or occasional players. Selling due to lack of use. Ships with protective covers. Great value for two quality rackets.',
        image_url=image_url['Tennis Racket Pair'],
        start_bid=30,
        is_active=True,
        owner=users.objects.get(username='mike'),
        category=categories.objects.get(name='Sports')
    )

    auctions.objects.create(
        title='Golf Club Starter Set',
        description='Beginner golf club set including driver, irons, putter, and stand bag. All clubs in good condition with minor wear. Bag has shoulder straps and several pockets. Used occasionally at the driving range. Ideal for someone getting into the game. Selling due to upgrade. Local pickup preferred.',
        image_url=image_url['Golf Club Starter Set'],
        start_bid=100,
        is_active=True,
        owner=users.objects.get(username='james'),
        category=categories.objects.get(name='Sports')
    )


def remove_data(apps, schema_editor):
    auctions = apps.get_model('auctions', 'Auction')
    auctions.objects.filter(title='Playstation 5').delete()
    auctions.objects.filter(title='Xbox Series X').delete()
    auctions.objects.filter(title='Nintendo Switch').delete()
    auctions.objects.filter(title='MacBook Pro').delete()
    auctions.objects.filter(title='Dell XPS 13').delete()
    auctions.objects.filter(title='Star Wars Lego').delete()
    auctions.objects.filter(title='Barbie Dreamhouse').delete()
    auctions.objects.filter(title='Hot Wheels Track Set').delete()
    auctions.objects.filter(title='Nerf Rival Blaster').delete()
    auctions.objects.filter(title='Monopoly Deluxe Edition').delete()
    auctions.objects.filter(title='Minecraft LEGO Set').delete()
    auctions.objects.filter(title='Uno Giant Edition').delete()
    auctions.objects.filter(title='Dyson V15 Vacuum').delete()
    auctions.objects.filter(title='Keurig Coffee Maker').delete()
    auctions.objects.filter(title='Instant Pot Duo').delete()
    auctions.objects.filter(title='Ninja Air Fryer').delete()
    auctions.objects.filter(title='Roomba i7 Robot Vacuum').delete()
    auctions.objects.filter(title='Brita Water Pitcher').delete()
    auctions.objects.filter(title='Bamboo Cutting Board').delete()
    auctions.objects.filter(title='Ironing Board').delete()
    auctions.objects.filter(title='Weber Charcoal Grill').delete()
    auctions.objects.filter(title='Coleman Camping Stove').delete()
    auctions.objects.filter(title='Yeti Cooler').delete()
    auctions.objects.filter(title='Folding Camping Chairs').delete()
    auctions.objects.filter(title='Hammock with Stand').delete()
    auctions.objects.filter(title='Garden Hose Reel').delete()
    auctions.objects.filter(title='Rawlings Baseball Bat').delete()
    auctions.objects.filter(title='Nike Soccer Ball').delete()
    auctions.objects.filter(title='Basketball Hoop Set').delete()
    auctions.objects.filter(title='Trek Mountain Bike').delete()
    auctions.objects.filter(title='Yoga Mat Set').delete()
    auctions.objects.filter(title='Adjustable Dumbbells').delete()
    auctions.objects.filter(title='Ping Pong Table').delete()
    auctions.objects.filter(title='Skateboard Helmet').delete()
    auctions.objects.filter(title='Tennis Racket Pair').delete()
    auctions.objects.filter(title='Golf Club Starter Set').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_remove_category_auctions_auction_category_and_more"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
