# Generated by Django 5.2 on 2025-04-21 01:53

from django.db import migrations, models
import random

comments = [
    "Is this the final price or are you open to negotiation?",
    "This looks amazing! What year was it manufactured?",
    "Does it come with the original packaging?",
    "How soon can you ship it after the auction ends?",
    "I used to have one just like this—brings back memories!",
    "Can you confirm if there are any scratches or dents?",
    "Absolutely love the design. Following this one closely.",
    "Are there any guarantees or warranties included?",
    "Has it been tested and does it still work?",
    "I’ve been looking for this exact model for weeks!",
    "Thanks for listing this—super hard to find lately.",
    "Do you offer combined shipping if I win multiple items?",
    "Can you provide more pictures of the bottom and back?",
    "Looks great. Any known issues I should be aware of?",
    "What’s the reason you're letting it go?",
    "Would love to know if it’s pet-free and smoke-free.",
    "This looks brand new. Has it ever been used?",
    "Perfect gift idea. Watching closely.",
    "I’m not familiar with this brand—is it reliable?",
    "Can you share the dimensions? Need to make sure it fits.",
    "Looks vintage—any idea what year it’s from?",
    "Is there a reserve price I should know about?",
    "Great color. Does it look the same in natural light?",
    "Super excited to bid on this!",
    "What’s the return policy if it arrives damaged?",
    "This could complete my collection!",
    "I’m curious—where did you originally get this from?",
    "Looks like a collector’s item. Is it limited edition?",
    "Any chance you’ll relist if it doesn’t sell?",
    "How does the condition compare to new?",
    "Not sure if I missed it, but is there a manual included?",
    "Was it stored in a climate-controlled environment?",
    "Thanks for including detailed photos!",
    "Looks like it’s in excellent shape.",
    "Hope I win this one!",
    "Does it come from a smoke-free home?",
    "Is local pickup available?",
    "Can you verify the serial number?",
    "Looks too good to be true!",
    "Can’t wait to see how this auction ends.",
    "Nice! Is this the original finish?",
    "The shipping seems high—any flexibility?",
    "What’s your experience with this item?",
    "Can you list the exact model number?",
    "This brings back childhood memories!",
    "Rare to find one in this condition.",
    "Is international shipping available?",
    "How long have you had it?",
    "I’ve got a similar one—this is a great deal.",
    "Wish I’d seen this last week!",
    "Just placed my bid!",
    "Any known defects or issues?",
    "This would be perfect for my office.",
    "The bidding is heating up!",
    "Have you used it recently?",
    "Was it purchased new or secondhand?",
    "This would be great for a gift.",
    "Can I message you for more info?",
    "Are all the parts included?",
    "Hope it’s still here by the weekend!",
    "Is that a scratch near the logo?",
    "Do you ship with tracking?",
    "Looks better than I expected.",
    "Can I see a close-up of the corners?",
    "Are there any marks or discoloration?",
    "Thanks for answering everyone’s questions.",
    "Watching this—don’t want to miss out!",
    "Looks legit. Tempted to bid now.",
    "Will you ship it safely bubble-wrapped?",
    "Was it ever repaired or refurbished?",
    "Does the price include accessories?",
    "This would go great in my living room.",
    "Looks like it’s never been opened.",
    "Awesome listing—thanks!",
    "How soon can it be delivered?",
    "You’ve got good taste in items.",
    "Will you accept returns if it’s not as described?",
    "Just added to my watchlist.",
    "Do you have more like this?",
    "This is exactly what I’ve been searching for.",
    "Very cool piece. Where did you find it?"
]

long_comments = [
    """This item looks absolutely stunning. The craftsmanship is evident from the photos, and it seems to have been well cared for over the years. I’m particularly interested in knowing more about its provenance—has it been in your family long, or did you acquire it through another collector? I’m a serious buyer and have been searching for a piece like this for months now. If you can confirm authenticity and give a bit more background, I’ll likely be placing a competitive bid. Also, are there any imperfections or restoration efforts you’re aware of?""",
    """Wow, this listing caught my eye immediately. The details in the product description are helpful, but I’d really appreciate it if you could elaborate on the condition a bit more. For example, has it ever been exposed to high humidity or temperature extremes? I'm based overseas, so shipping and handling are very important to me—can you confirm how it will be packaged and if insurance is included? I’ve had a few items arrive damaged in the past, and I just want to be sure everything will arrive safely. Looking forward to your reply!""",
    """This is one of the most unique items I’ve come across in quite some time. I'm very intrigued by both its aesthetic and its functional condition. You mentioned it still works, but has it been recently tested? And if so, under what circumstances? I collect similar items and would like to know if there’s any maintenance required before use. Also, any idea if replacement parts are still available for this make/model? It's always a risk buying older pieces, but this one looks worth it. Thanks for taking the time to list it—hope you don’t mind all the questions.""",
    """I just wanted to say thank you for such a well-presented listing. The high-quality images and detailed description are really appreciated, especially in a marketplace where so many sellers skimp on that sort of thing. I have a few questions: Is the item being sold as-is, or is there some kind of return policy if it doesn’t match the listing? I’m also curious if this was used daily, occasionally, or just kept in storage. If there’s a story behind it, I’d love to hear it! Items like this often have rich histories that make them even more special.""",
    """I've been looking for this exact piece for quite a while, and I'm excited to have finally found it here. From what I can see, the condition looks great, but I would appreciate a closer photo of the bottom side—sometimes that area reveals more about the wear and tear. Also, can you confirm if this item has any unusual smells, like mustiness or chemical odors? I collect vintage items and always check for that before bidding. Lastly, will you be offering combined shipping if I win another one of your items? Thanks so much for your time and effort!""",
    """Really impressive listing here. The item has great visual appeal and looks to be in very solid condition. I noticed you’ve listed it as ‘used’—could you clarify exactly how it was used and how often? Also, is everything still in working order, and are there any operational quirks or things I should be aware of? Items of this age sometimes come with their own personality, which I love, but it’s always good to know ahead of time. I’m also wondering if you accept alternative payment methods outside the platform for large transactions. Let me know. Thanks again for sharing this piece!""",
    """This is such a beautiful find! The detailing really stands out in the photos, and I imagine it looks even better in person. I’m seriously considering placing a bid but had a couple of questions first. Is this item part of a larger set, or is it a one-off? Also, has it been professionally appraised recently? It would help justify the cost if there’s some formal valuation attached. Finally, I’m curious about its origin—was it handmade, and if so, by whom? Sometimes knowing the creator adds an emotional layer of value for collectors like me.""",
    """I just wanted to say this is probably one of the most professional listings I've seen on this site. Great photos, clear description, and you seem really responsive in the comments—huge plus for potential buyers. I’m a bit new to collecting, so I hope you don’t mind a few questions. Is there anything about this item that might not be obvious from the pictures, like internal damage or hidden flaws? Also, how long have you owned it, and do you know if it’s had any previous repairs? I’m interested in buying and want to make an informed decision.""",
    """You’ve really done a fantastic job with this listing. Everything about the item is beautifully displayed and described. I have one concern: the shipping cost seems a little higher than I expected—could you explain what’s included in that price? I’m happy to pay a premium for careful packaging, especially for fragile items, but I want to make sure I understand what I’m getting. Also, do you offer expedited shipping for international buyers? I live in Europe and would love to get this before the holidays if possible. Let me know, and thanks again for offering such a rare item!""",
    """I’ve been bidding on a few similar items lately and this one definitely stands out. The quality looks exceptional and I appreciate the multiple photo angles. I’d love to know more about how you acquired it—was it a personal piece or did you find it through an estate sale? That kind of history is always interesting to me. Also, are you open to private offers outside of the auction platform, or are you strictly going by the bidding rules? Just curious, since I’d be willing to make a competitive offer upfront. Thanks again, and I’ll be watching closely!""",
    """This item is absolutely gorgeous and looks to be in excellent condition. I’m very interested but just want to double-check a few things. First, could you let me know if the photos accurately reflect the color? Sometimes lighting can be tricky. Also, has it ever been stored in a damp environment or around pets? I have allergies, so that kind of thing is important to me. It really looks like a rare piece, and I'm thrilled to have found it. I’d also love to know how you came across it—estate sale, personal collection, etc.?""",
    """I'm really intrigued by this listing—it seems like something with real character. The photos do a good job showing the exterior, but could you upload one or two shots of the inside or underside of the item? I’ve seen similar listings in the past, but many were in poor condition, and this one seems to be an exception. It looks like a collector’s dream, honestly. Is there any way you can confirm the authenticity? I know that can be hard sometimes without paperwork, but even a bit of background would help. Looking forward to your reply!""",
    """This looks like a fantastic piece! The wear on the surface gives it a certain charm that I really like. Can you tell me more about how it was used? For example, was it in regular use, or did it sit on display most of the time? I’m considering placing a bid but would like a little more insight into its history and usage. Also, would you be open to local pickup? I live about an hour away and would prefer to collect it in person rather than risk shipping damage. Thanks in advance for any additional details you can provide.""",
    """Thanks for such a thoughtful and thorough listing. I really appreciate the time you've taken with the photography and description—it makes a huge difference to buyers like me. One question I had is about the functionality: you mention that it’s in working condition, but has it been tested recently? I’ve had a few experiences where items worked fine last year but had issues after storage. Also, do you know if replacement parts are easy to come by if needed? This looks like something I’d want to use, not just display. Hoping to hear from you soon!""",
    """This is one of those items that immediately brings back memories. I had something like this growing up, and the moment I saw it, I felt a wave of nostalgia. I’m seriously considering bidding, but could you clarify a couple of things? Is everything original, or have any parts been replaced or restored? Also, how would you rate its condition on a scale of 1 to 10? I’m mostly buying for sentimental value, but it would be great to have a sense of what to expect. Either way, great listing. Thanks for making this available!""",
    """Beautiful piece! I can tell from the photos that this has been very well taken care of. I’m interested in bidding but would like to know how it has been stored—indoors, in a temperature-controlled space, or maybe an attic or garage? I’ve found that environment really makes a difference for older items. Also, can you confirm whether this will be insured during shipping? I’ve had things lost in the mail before and just want to be cautious. Everything about this item looks wonderful otherwise, and I wouldn’t want to miss the chance to bid on it.""",
    """I’m really impressed by the level of detail in your listing. You’ve done a great job describing the item, and I especially appreciate the photos showing every angle. That said, I’m still a bit uncertain about the scale—can you share exact measurements? I’ve made the mistake of buying something that looked big in photos but was actually quite small in person. Also, could you clarify if this item has any unusual odors (like smoke or mildew)? I know it’s an odd question, but it’s something I always check on before buying vintage or used goods. Thanks again!""",
    """Such a cool item. I haven’t seen one in this condition in a while! One quick question—are all the components or accessories that originally came with it still included, or is anything missing? I’m a bit of a stickler for completeness when it comes to collectibles. Also, are you the original owner? I like knowing the item’s backstory if possible. It really helps add context and value for me. I appreciate all the effort you’ve put into this listing—it stands out for all the right reasons. Hoping to hear from you before the auction ends!""",
    """This item is stunning, and I can already imagine it fitting perfectly in my home. Before placing a bid, though, I have a couple of questions. First, are there any repairs that have been done to this item? Sometimes sellers forget to mention small fixes that could affect the long-term value. Second, what is the approximate weight? That would help me estimate shipping costs better. Lastly, is there a story behind it? Sometimes I fall in love with an item even more when I know a bit about its history or why you’re parting with it. Thanks!""",
    """This might be the exact piece I’ve been looking for. I’ve checked the photos and the description several times and it seems to meet all my criteria. I just have one concern: I need to know if this comes from a pet-free, smoke-free environment. I have pretty severe allergies, and even trace amounts can be an issue. Also, could you let me know the exact shipping service you'll be using and whether tracking will be included? I’ve had trouble with lost packages before, and it’s important that this one arrives safely. Really excited to potentially own this!""",
    """I wanted to compliment you on this listing—it’s clear, well-written, and thorough. That said, I still have a couple of questions before I decide to bid. Can you confirm if this is the original finish, or has it been refinished or painted at any point? And do you know if it’s safe for outdoor use or strictly for indoor display? I’m planning to use it in a very specific spot, and knowing that would really help me make a decision. It’s such a charming piece, and I’d hate to miss out. Let me know when you get a chance!""",
    """Gorgeous item and very nicely presented. Just wondering, do you know what the estimated age is? You mentioned it’s vintage, but it would be helpful to know more precisely what time period it's from. That really affects the value in my eyes. Also, is this a one-of-a-kind item, or do you have others like it that you might be listing soon? I’m building a themed room and would be interested in related pieces. I’m bookmarking this one for sure and will likely bid, but would love to hear your thoughts on the above before I do.""",
    """What an amazing find! The pictures show it off beautifully, and I appreciate the lighting and close-up details. Before I commit, I’d like to know whether you’ve cleaned or polished the item in any way for the listing photos. Sometimes treatments can change the surface or finish, and I just want to be sure it looks the same in person. Also, is there any flexibility in the shipping options? I might prefer a courier service over standard mail if that’s possible. Great job putting this listing together—it really stands out from the rest. Hoping to hear back soon!""",
    """This is the kind of item that doesn’t show up very often. I’m a serious collector and this fits perfectly with a series I’ve been working on for years. The condition seems quite good, but do you know if there’s any fading, especially on the back or sides that aren't shown in the images? I try to only buy items that are consistent all around. Also, is there any documentation that comes with this piece—manuals, certificates, tags, anything at all? Thanks again for the great listing. This could end up being one of the highlights of my collection!""",
    """Impressive listing! I’m not familiar with this particular brand, but I’ve been researching it and it seems to have a solid reputation. Could you provide any additional insights into the manufacturer or where the item was originally purchased? Even an approximate year or region would help. I like to keep detailed records of everything in my collection. Also, I’ve noticed that many vintage items have small imperfections that aren’t always visible in photos. Could you describe any areas that you think might need a closer look or additional care? Thanks in advance for your help!"""
]

class Migration(migrations.Migration):

    def add_data(apps, schema_editor):
        user_index = 0
        comment_index = 0

        Auction = apps.get_model('auctions', 'Auction')
        Comment = apps.get_model('auctions', 'Comment')
        User = apps.get_model('auctions', 'User')

        for auction in Auction.objects.all():
            for _ in range(random.randint(1, 5)):
                user = User.objects.get(id=user_index + 2)
                user_index = (user_index + 1) % 5

                if comment_index % 3 == 0:
                    content = random.choice(long_comments)
                else:
                    content = random.choice(comments)
                comment_index += 1

                Comment.objects.create(auction=auction, user=user, content=content)


    def remove_data(apps, schema_editor):
        Comment = apps.get_model('auctions', 'Comment')
        Comment.objects.all().delete()


    dependencies = [
        ('auctions', '0005_add_auction_data'),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
