# Generated by Django 5.2 on 2025-04-21 10:21

from django.db import migrations, models
import random


class Migration(migrations.Migration):

    def add_data(apps, schema_editor):
        user_index = 0
        
        Auction = apps.get_model('auctions', 'Auction')
        Bid = apps.get_model('auctions', 'Bid')
        User = apps.get_model('auctions', 'User')

        for auction in Auction.objects.all():

            if random.randint(0, 1) == 1:
                continue

            amount = auction.start_bid
            for _ in range(random.randint(1, 5)):
                user = User.objects.get(id=user_index + 2)
                user_index = (user_index + 1) % 5
                
                if user == auction.owner:
                    user = User.objects.get(id=user_index + 2)
                    user_index = (user_index + 1) % 5

                amount += (10 * random.randint(1, 5))
                Bid.objects.create(auction=auction, user=user, amount=amount)


    def remove_data(apps, schema_editor):
        Bid = apps.get_model('auctions', 'Bid')
        Bid.objects.all().delete()


    dependencies = [
        ('auctions', '0006_add_comment_data'),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
