# Generated by Django 5.2 on 2025-04-21 10:21

from django.db import migrations, models
import random


class Migration(migrations.Migration):

    def add_data(apps, schema_editor):
        user_index = 0
        
        Auction = apps.get_model('auctions', 'Auction')
        Bid = apps.get_model('auctions', 'Bid')
        User = apps.get_model('auctions', 'User')

        for auction in Auction.objects.all():

            if random.randint(0, 2) == 0:
                continue

            amount = auction.start_bid
            for _ in range(random.randint(1, 5)):
                user = User.objects.get(id=user_index + 2)
                user_index = (user_index + 1) % 5
                
                if user == auction.owner:
                    user = User.objects.get(id=user_index + 2)
                    user_index = (user_index + 1) % 5

                amount += (10 * random.randint(1, 5))
                Bid.objects.create(auction=auction, user=user, amount=amount)

        last_category = -1
        for auction in Auction.objects.all()[::-1]:
            if auction.category.id == last_category:
                continue

            highest_bid = Bid.objects.filter(auction=auction).order_by('-amount').first()
            if highest_bid:
                amount = highest_bid.amount + (10 * random.randint(1, 5))
                Bid.objects.create(auction=auction, user=highest_bid.user, amount=amount, winning_bid=True)
                auction.is_active = False
                auction.save()
                last_category = auction.category.id


    def remove_data(apps, schema_editor):
        Bid = apps.get_model('auctions', 'Bid')
        Bid.objects.all().delete()


    dependencies = [
        ('auctions', '0006_add_comment_data'),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
