# Generated by Django 5.2 on 2025-04-21 10:36

from django.db import migrations, models
import random


class Migration(migrations.Migration):

    def add_data(apps, schema_editor):
        user_index = 0
        
        Auction = apps.get_model('auctions', 'Auction')
        Watchlist = apps.get_model('auctions', 'Watchlist')
        User = apps.get_model('auctions', 'User')

        for auction in Auction.objects.all():
            for _ in range(random.randint(1, 5)):

                if random.randint(0, 3) != 0:
                    continue
                
                user = User.objects.get(id=user_index + 2)
                user_index = (user_index + 1) % 5
                
                if user == auction.owner:
                    continue

                Watchlist.objects.create(auction=auction, user=user)


    def remove_data(apps, schema_editor):
        Watchlist = apps.get_model('auctions', 'Watchlist')
        Watchlist.objects.all().delete()


    dependencies = [
        ('auctions', '0007_add_bid_data'),
    ]

    operations = [
         migrations.RunPython(add_data, reverse_code=remove_data)
    ]
