# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
import json
from pathlib import Path


def add_data(apps, schema_editor):
    
    root_folder = Path(__file__).parent.parent
    json_file_path = root_folder / 'data' / 'categories.json'
    
    with open(json_file_path, 'r') as file:
        category_data = json.load(file)
    
    category_model = apps.get_model('quizly', 'Category')
    
    # Create category objects from the JSON data
    for name, description in category_data.items():
        category_model.objects.create(name=name, description=description)


def remove_data(apps, schema_editor):
    categories = apps.get_model('quizly', 'Category')
    categories.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0003_add_users"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
