# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_data(apps, schema_editor):
    categories = apps.get_model('quizly', 'Category')
    categories.objects.create(name='Python')
    categories.objects.create(name='JavaScript')
    categories.objects.create(name='Java')
    categories.objects.create(name='C')
    categories.objects.create(name='C++')
    categories.objects.create(name='C#')
    categories.objects.create(name='TypeScript')
    categories.objects.create(name='Go')
    categories.objects.create(name='Rust')
    categories.objects.create(name='PHP')
    categories.objects.create(name='Swift')
    categories.objects.create(name='Kotlin')
    categories.objects.create(name='Ruby')
    categories.objects.create(name='SQL')
    categories.objects.create(name='Shell')
    

def remove_data(apps, schema_editor):
    categories = apps.get_model('quizly', 'Category')
    categories.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0003_add_users"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
