# Generated by Django 5.2 on 2025-04-15 00:03

import random
from django.db import migrations
from django.utils import timezone
import datetime


def add_data(apps, schema_editor):
    quiz_attempt_model = apps.get_model('quizly', 'QuizAttempt')
    quiz_model = apps.get_model('quizly', 'Quiz')
    user_model = apps.get_model('quizly', 'User')

    users = list(user_model.objects.exclude(username='admin'))
    quizzes = list(quiz_model.objects.all())
    
    now = timezone.now()
    
    for quiz in quizzes:
        for user in users:
            if random.randint(0, 1) == 1:
                correct = random.randint(quiz.questions.count() // 2, quiz.questions.count())
                
                # Generate random date between quiz creation and now
                time_diff = (now - quiz.created_at).total_seconds()
                random_seconds = random.randint(0, int(time_diff))
                random_date = quiz.created_at + datetime.timedelta(seconds=random_seconds)
                
                quiz_attempt_model.objects.create(
                    user=user,
                    quiz=quiz,
                    correct=correct,
                    score=correct / quiz.questions.count() * 100,
                    date_taken=random_date,
                )

    
def remove_data(apps, schema_editor):
    quiz_attempt_model = apps.get_model('quizly', 'QuizAttempt')
    quiz_attempt_model.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0005_add_quizzes"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
