# Generated by Django 5.2 on 2025-05-09 00:25

import random
from django.db import migrations


def add_data(apps, schema_editor):
    saved_for_later_model = apps.get_model('quizly', 'SavedForLater')
    quiz_attempt_model = apps.get_model('quizly', 'QuizAttempt')
    quiz_model = apps.get_model('quizly', 'Quiz')
    user_model = apps.get_model('quizly', 'User')

    users = list(user_model.objects.exclude(username='admin'))
    quizzes = list(quiz_model.objects.all())
    
    for quiz in quizzes:
        for user in users:
            if random.randint(0, 1) == 1:
                
                # Dont save your own quiz for later
                if user == quiz.created_by:
                    continue
                
                # Don't save if the user has already attempted the quiz
                if quiz_attempt_model.objects.filter(user=user, quiz=quiz).exists():
                    continue

                saved_for_later_model.objects.create(
                    user=user,
                    quiz=quiz,
                )

    
def remove_data(apps, schema_editor):
    saved_for_later_model = apps.get_model('quizly', 'SavedForLater')
    saved_for_later_model.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0007_add_quiz_ratings"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
