# Generated by Django 5.2 on 2025-05-09 05:59

from django.db import migrations, models
import quizly.management.commands.build_faiss_index as faiss_index


class Migration(migrations.Migration):

    dependencies = [
        ('quizly', '0008_add_saved_for_later'),
    ]

    operations = [        
        migrations.RunPython(
            faiss_index.Command().handle, 
            reverse_code=migrations.RunPython.noop
        ),
    ]
