# Generated by Django 5.2 on 2025-05-05 23:30

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_data(apps, schema_editor):
    users = apps.get_model('network', 'User')
    users.objects.create(username='mike74', password=make_password('mike'), email='mike@example.com', first_name='Mike', last_name='Jones', is_superuser=True, is_staff=True)
    users.objects.create(username='bobster_42', password=make_password('bob'), email='bob@example.com', first_name='Bob', last_name='Carter', is_superuser=False)
    users.objects.create(username='emma_reads', password=make_password('emma'), email='emma@example.com', first_name='Emma', last_name='Wilson', is_superuser=False)
    users.objects.create(username='j_harris28', password=make_password('james'), email='james@example.com', first_name='James', last_name='Harris', is_superuser=False)
    users.objects.create(username='sally_cooks', password=make_password('sally'), email='sally@example.com', first_name='Sally', last_name='Mitchell', is_superuser=False)
    users.objects.create(username='alex_t_gamer', password=make_password('alex'), email='alex@example.com', first_name='Alex', last_name='Thompson', is_superuser=False)
    users.objects.create(username='lisa.brown22', password=make_password('lisa'), email='lisa@example.com', first_name='Lisa', last_name='Brown', is_superuser=False)
    users.objects.create(username='chris_d_coder', password=make_password('chris'), email='chris@example.com', first_name='Chris', last_name='Davis', is_superuser=False)
    users.objects.create(username='olivia_m_artist', password=make_password('olivia'), email='olivia@example.com', first_name='Olivia', last_name='Martinez', is_superuser=False)
    users.objects.create(username='dave_travels', password=make_password('david'), email='david@example.com', first_name='David', last_name='Garcia', is_superuser=False)
    users.objects.create(username='sarah_r_photos', password=make_password('sarah'), email='sarah@example.com', first_name='Sarah', last_name='Rodriguez', is_superuser=False)

def remove_data(apps, schema_editor):
    users = apps.get_model('network', 'User')
    users.objects.filter(username='mike74').delete()
    users.objects.filter(username='bobster_42').delete()
    users.objects.filter(username='emma_reads').delete()
    users.objects.filter(username='j_harris28').delete()
    users.objects.filter(username='sally_cooks').delete()
    users.objects.filter(username='alex_t_gamer').delete()
    users.objects.filter(username='lisa.brown22').delete()
    users.objects.filter(username='chris_d_coder').delete()
    users.objects.filter(username='olivia_m_artist').delete()
    users.objects.filter(username='dave_travels').delete()
    users.objects.filter(username='sarah_r_photos').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_post_like'),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
