# Generated by Django 5.2 on 2025-05-05 23:33

from django.db import migrations
import random
from datetime import datetime, timedelta

def add_data(apps, schema_editor):
    User = apps.get_model('network', 'User')
    Post = apps.get_model('network', 'Post')
    
    users = list(User.objects.all())

    sample_posts = [
        "Just completed an invigorating workout session at the gym! My muscles are buzzing with energy, and I'm pumped to conquer my to-do list today.",
        "Savoring the cozy comfort of a steaming cup of chamomile tea while rain gently taps against my window. It's the perfect afternoon to curl up with a good book and lose myself in a captivating story, wrapped in a soft blanket by the fireplace.",
        "Dreaming up my next travel adventure! Should I explore the vibrant streets of Tokyo or the serene beaches of Bali? Suggestions welcome!",
        "Whipped up a mouthwatering vegan stir-fry tonight with fresh veggies and a tangy peanut sauce. It was a culinary triumph! The kitchen was filled with the aroma of sizzling garlic and ginger, and I savored every bite of this colorful, plant-based masterpiece.",
        "Cherishing a heartwarming evening with family, filled with laughter, board games, and homemade pizza. These moments make life truly special.",
        "Immersed in a coding project that's pushing my skills to the limit. Building a sleek app that I can't wait to share! Hours fly by as I debug lines of code, design intuitive interfaces, and test features to ensure a smooth user experience for this exciting new tool.",
        "Witnessed a breathtaking sunset tonight, with hues of orange and pink painting the sky. Nature's beauty never ceases to amaze me.",
        "Unwinding with a playlist of soothing acoustic tunes after a hectic day. Music is my escape. Each melody washes away the stress of deadlines, as I sink into the couch, letting the gentle strums of the guitar and soft vocals carry me to a place of calm.",
        "Spent the day volunteering at the local animal shelter, walking dogs and cuddling kittens. Their joy reminds me why I love giving back.",
        "Transformed my cluttered workspace into a minimalist haven. A tidy desk really does spark clarity and focus! I organized papers, decluttered drawers, and added a small potted plant to bring life to the space, making it a perfect environment for productivity.",
        "Kicking off the morning with a rich cup of coffee and a gripping novel. There's no better way to start the day.",
        "Wandered through the city today and stumbled upon a quaint bookstore tucked away in an alley. Found a rare poetry collection! The shop was filled with the scent of old books, and I spent hours browsing shelves, chatting with the owner about classic literature.",
        "Got my hands dirty in the garden today, planting vibrant flowers and tending to my veggie patch. Connecting with nature is pure therapy.",
        "Planning a cozy movie marathon this weekend with popcorn and blankets. Any must-watch film recommendations? I’m stocking up on snacks, dimming the lights, and creating a cozy nest of pillows for an epic weekend of cinematic adventures with friends.",
        "Strumming my way through guitar lessons. My fingers are sore, but I'm determined to master that tricky chord progression!",
        "Took a refreshing walk in the park, letting the crisp air clear my mind. Nature always has a way of resetting me. The rustling leaves, chirping birds, and cool breeze reminded me to slow down and appreciate the simple beauty around me.",
        "Diving into photography as a new hobby, capturing candid moments around town with my camera. Every shot tells a story.",
        "Baked a batch of gooey chocolate chip cookies today. The kitchen smells divine, and I can't wait to share them! The warm, buttery aroma filled the house as I mixed dough, and I snuck a taste of the batter before baking perfect, golden cookies for my neighbors.",
        "Hosted a lively game night with friends, filled with laughter and friendly competition. Nothing beats these fun-filled evenings.",
        "Visited a bustling farmer's market this morning, picking up fresh strawberries and homemade jam. Supporting local vendors feels great! I chatted with farmers, sampled artisanal cheeses, and filled my basket with vibrant produce for a week of healthy meals.",
        "Feeling inspired after a creative writing workshop that sparked new ideas for my next short story. Time to put pen to paper!",
        "Had a productive study session today, diving deep into my coursework. Each step forward feels like a small victory. I tackled complex concepts, took detailed notes, and even squeezed in a quick review session to solidify my understanding before the next exam.",
        "Soaking up the sun at the beach, with waves crashing and seagulls soaring overhead. This is my kind of paradise.",
        "Tried meditation for the first time this morning, focusing on my breath and finding a sense of calm. I'm hooked! Sitting cross-legged in the quiet of my room, I let go of racing thoughts, guided by a soothing app that helped me find inner peace.",
        "Decluttered my closet, donating clothes I no longer wear. Embracing a simpler wardrobe feels incredibly liberating.",
        "Bought a vibrant print from a local artist at a gallery opening. Supporting creativity adds color to my home! The bold colors and unique design caught my eye, and I loved hearing the artist’s story behind their work at the lively exhibition.",
        "Cooked a delicious dinner using fresh basil and rosemary from my garden. Homegrown herbs make every dish special.",
        "Enjoyed a quiet evening piecing together a 1000-piece puzzle. It's both relaxing and a fun mental challenge. The intricate design slowly came together as I sipped hot cocoa, losing track of time in the satisfying click of each piece finding its place.",
        "Planning a surprise birthday party for my best friend! Keeping it hush-hush while organizing the perfect celebration.",
        "Attended a fascinating seminar on sustainable living, learning practical tips like composting and reducing waste. Small changes, big impact! I’m now inspired to start a compost bin, shop secondhand, and cut down on single-use plastics in my daily routine.",
        "Started my day with an energizing early morning run through the neighborhood. The sunrise views were worth the early wake-up.",
        "Explored a new hiking trail today, winding through lush forests and rewarding me with stunning mountain vistas. Nature never disappoints! The trail was challenging, with steep climbs and rocky paths, but the panoramic views and fresh pine air made every step worthwhile.",
        "Attended a thought-provoking lecture on artificial intelligence, exploring its potential to revolutionize industries. The future is exciting!",
        "Tried my hand at pottery, shaping clay into a wonky but charming bowl. It's messy, creative, and so much fun! The wheel spun as I molded the clay, my hands covered in slip, and I laughed at my lopsided creation that’s now a quirky addition to my kitchen.",
        "Had a delightful picnic in the park with friends, complete with homemade sandwiches and lemonade. Good food, great company!",
        "Spent the afternoon reading poetry under a shady oak tree, letting the words wash over me. These moments feel like pure magic. The rhythm of the verses and the rustle of leaves created a serene escape, where I could reflect and dream in the dappled sunlight.",
        "Built a sturdy birdhouse for my backyard, painting it a bright blue. Can't wait to see which feathered friends move in!",
        "Practicing calligraphy with a dip pen and ink, crafting elegant letters. It's a beautiful blend of patience and creativity. Each stroke requires focus, and I’m experimenting with flourishes to create personalized cards that add a touch of elegance to my gifts.",
        "Visited a science museum today, marveling at interactive exhibits and learning about space exploration. Curiosity ignited!",
        "Made sweet strawberry jam from fresh berries I picked. The kitchen smells like summer, and the jars look so inviting! I simmered the fruit with sugar, stirring patiently as it thickened, and now I have homemade jars to share with family and friends.",
        "Gazed at a dazzling starry sky tonight, feeling small yet connected to the vast universe. Stargazing always humbles me.",
        "Incorporated yoga into my morning routine, stretching and breathing to find balance. My body and mind feel rejuvenated. Flowing through sun salutations in the soft morning light, I focused on each pose, feeling stronger and more centered with every breath.",
        "Took a scenic bike ride along the river, with cool breezes and beautiful views. It's the perfect way to recharge.",
        "Attempting a digital detox this weekend, swapping screens for real-world experiences. Wish me luck staying unplugged! I’m planning to hike, read physical books, and have face-to-face chats with friends to reconnect with the tangible world around me.",
        "Learned basic car maintenance, like changing a tire and checking oil. Empowering to know I can handle these tasks!",
        "Visited my grandparents and listened to their stories of the past. Their wisdom and warmth are treasures I'll always cherish. Over tea, they shared tales of their youth, from wartime struggles to joyful dances, painting vivid pictures of a bygone era.",
        "Crafted colorful friendship bracelets, weaving intricate patterns. It's a nostalgic hobby that brings back childhood memories!",
        "Watched a captivating local theater production, supporting talented actors and a heartfelt story. The arts are alive! The stage came alive with emotion, and I was moved by the actors’ passion, staying for a talkback to learn about their creative process.",
        "Experimented with brewing kombucha at home, mixing tea and a SCOBY. It's a fun, fizzy science project!",
        "Took a day trip to a charming nearby town, exploring historic streets and cozy cafes. New places, new perspectives! I wandered cobblestone paths, sipped latte at a family-owned cafe, and discovered a tiny museum that revealed the town’s rich history.",
        "Started learning sign language to communicate more inclusively. Practicing the alphabet is surprisingly fun!",
        "Laid back in the grass, cloud watching and spotting shapes in the sky. It's a simple way to spark imagination. The fluffy clouds drifted lazily, forming dragons and castles, as I let my mind wander in the peacefulness of a warm afternoon.",
        "Built an epic sandcastle at the beach, complete with moats and towers. Channeling my inner architect was a blast!",
        "Tried mindfulness coloring, filling intricate designs with vibrant colors. It's a surprisingly calming way to unwind. Each stroke of the pencil melted away stress, as I blended hues to create a mandala that now hangs proudly on my wall.",
        "Took a cheese-tasting class, sampling everything from creamy brie to sharp cheddar. My taste buds are in heaven!",
        "Strolled through a botanical garden, admiring exotic plants and fragrant flowers. Nature's diversity is stunning! I meandered along winding paths, snapping photos of orchids and learning about rare species, completely immersed in the lush greenery.",
        "Crafted homemade lavender candles to give as gifts. The soothing scent fills my home as I pour the wax.",
        "Started knitting a cozy scarf, learning to cast on and purl. It's a relaxing hobby for chilly evenings. The rhythmic click of needles and soft yarn in my hands create a meditative calm, as I work toward a warm accessory for winter.",
        "Indulged in a street food festival, tasting spicy tacos and sweet crepes. My stomach's happy, and so am I!",
        "Went geocaching in the park, hunting for hidden treasures with my GPS. It's like a real-world adventure game! I followed coordinates through winding trails, uncovering a small cache with trinkets and a logbook, feeling like an explorer on a quest.",
        "Learned origami, folding paper into delicate cranes and flowers. Turning a flat sheet into art is magical!",
        "Spent the day at the library, surrounded by shelves of books. Found a gripping mystery novel to dive into! The quiet hum of the library and the scent of pages drew me in, as I lost myself in a thrilling whodunit for hours.",
        "Made luxurious homemade soap with oatmeal and honey. My bathroom feels like a spa now!",
        "Delved into local history at a museum, uncovering stories of my town's past. Every artifact has a tale to tell! From old photographs to antique tools, I pieced together how my community grew, feeling a deeper connection to my roots.",
        "Gathered around a crackling bonfire with friends, roasting marshmallows and sharing stories. Perfect night!",
        "Tried bird watching with binoculars, spotting colorful cardinals and sparrows. Nature's little performers are everywhere! I sat quietly by the feeder, noting each bird’s unique markings and songs, marveling at the lively ecosystem in my backyard.",
        "Took a basic first aid course, learning CPR and wound care. These skills could make a real difference someday.",
        "Visited an aquarium, mesmerized by graceful jellyfish and vibrant coral reefs. The ocean is a world of wonder! I stood in awe as fish darted through swaying anemones, learning about conservation efforts to protect these delicate underwater ecosystems.",
        "Created pressed flower art, preserving delicate petals in frames. It's a beautiful way to capture nature's beauty.",
        "Learned a few magic tricks to entertain friends at our next gathering. Practicing my sleight of hand! I’m mastering card tricks and coin vanishes, rehearsing in front of a mirror to perfect the flair that’ll wow everyone at the next party.",
        "Joined a pottery painting class, decorating mugs with colorful glazes. Unleashing my inner artist feels great!",
        "Tackled indoor rock climbing, scaling walls and pushing my limits. It's a thrilling full-body workout! Each grip and foothold tested my strength, and reaching the top felt like a triumph, leaving me eager to climb higher next time.",
        "Studied constellations, mapping out Orion and the Big Dipper in the night sky. The stars are my guide tonight!",
        "Visited a historical landmark, walking through centuries-old halls. History feels alive in these places! Stone walls and creaky floors whispered stories of the past, as I imagined the lives of those who walked there long before me.",
        "Crafted tiny terrariums, layering moss and succulents in glass jars. These mini ecosystems are adorable!",
        "Practiced juggling with three balls, slowly getting the hang of it. It's a fun way to boost coordination! Each toss and catch sharpens my focus, and I’m already dreaming of adding a fourth ball to the mix for an even bigger challenge.",
        "Laughed until my sides hurt at a comedy show. The comedians were spot-on, and the energy was electric!",
        "Tried urban sketching, drawing bustling city scenes with pen and ink. Capturing life on paper is exhilarating! I sat on a busy street corner, sketching vendors and passersby, each line bringing the vibrant urban pulse to life on my page.",
        "Explored wine tasting, savoring notes of oak and berry in each sip. It's a delicious way to learn!",
        "Visited a wildlife sanctuary, observing deer and foxes in their natural habitat. Respecting wildlife is humbling. I watched quietly as animals roamed freely, learning about their behaviors and the sanctuary’s efforts to protect these precious creatures.",
        "Wove intricate dreamcatchers with feathers and beads. They add a bohemian vibe to my room!",
        "Started learning basic coding concepts, writing my first lines of Python. Understanding tech is empowering! I’m building simple programs, troubleshooting errors, and feeling thrilled as each script runs successfully, opening doors to a new world of skills.",
        "Attended a composting workshop at a local farm, learning how to turn scraps into rich soil. Sustainability starts at home!",
        "Tried paddleboarding on the lake, wobbling but finding my balance. The water and sunshine were perfect! Gliding across the calm surface, I soaked in the serene views of distant trees and felt a rush of pride mastering this new water sport.",
        "Studied different architectural styles, from Gothic arches to modern minimalism. Buildings tell stories too!",
        "Browsed a lively flea market, finding vintage records and quirky trinkets. Treasure hunting is so rewarding! I haggled with vendors, unearthed a retro vinyl album, and found a unique lamp that now adds character to my living room.",
        "Experimented with natural dyes, using beets and turmeric to color fabric. The results are vibrant and eco-friendly!",
        "Learned basic self-defense techniques, feeling more confident and prepared. Safety first! Practicing blocks and strikes in a class empowered me, and I’m committed to building these skills to stay safe in any situation.",
        "Swayed to smooth jazz at a local club, sipping a mocktail and soaking in the vibes. Music speaks to the soul!",
        "Tried glass blowing, shaping molten glass into a delicate ornament. It's a fiery, fascinating craft! The glowing furnace and careful breath control mesmerized me, as I crafted a shimmering piece that captures light beautifully.",
        "Learned about beekeeping and the vital role bees play in our ecosystem. These pollinators are incredible!",
        "Strolled through a sculpture park, admiring bold metal and stone artworks under the open sky. Art inspires! Each piece told a story, from abstract forms to lifelike figures, sparking my imagination as I wandered through the serene park.",
        "Started a bullet journal to organize my goals and track habits. The colorful layouts are so satisfying to create!",
        "Enjoyed a serene evening painting watercolors, blending soft blues and pinks. Art is my therapy. I set up my easel by the window, letting the fading light guide my brush as I created a dreamy landscape that captures my calm mood.",
        "Took a virtual cooking class, mastering a creamy mushroom risotto. My kitchen smells like a gourmet restaurant!",
        "Redecorated my living room with thrifted furniture and cozy textiles. It feels like a whole new space! I scoured secondhand shops for unique pieces, adding plush cushions and a woven rug to create a warm, inviting haven for relaxation.",
        "Joined a book club and had a lively discussion about a classic novel. Love connecting over stories!",
        "Tried my hand at soap carving, shaping delicate flowers from bars of soap. It's surprisingly meditative! Each careful cut revealed intricate petals, and the smooth texture of the soap made this quiet craft a soothing way to unwind.",
        "Spent the day kayaking on a calm river, surrounded by lush greenery. Paddling is my new favorite workout!",
        "Attended a workshop on mindfulness, practicing gratitude and breathing exercises. Feeling centered and calm. I journaled about things I’m thankful for, guided by a teacher who showed us how to stay present in each moment, reducing stress.",
        "Planted a small herb garden on my balcony, with mint, thyme, and cilantro. Fresh flavors at my fingertips!",
        "Experimented with tie-dye, creating vibrant patterns on old t-shirts. My wardrobe just got a colorful upgrade! I swirled dyes in bold spirals, transforming plain shirts into wearable art that’s perfect for casual days and summer festivals.",
        "Watched a documentary about marine life, learning about coral reefs and sea turtles. The ocean is so fragile yet beautiful!",
        "Tried my hand at macrame, knotting cords into a boho wall hanging. Crafting is my happy place! I wove intricate patterns with soft cotton rope, creating a textured piece that adds a cozy, handmade touch to my living space.",
        "Joined a community cleanup at the beach, picking up trash and protecting marine life. Small actions matter!",
        "Baked a decadent chocolate cake for a friend's birthday. The frosting swirls were a work of art! I layered rich ganache and piped delicate designs, making a showstopping dessert that had everyone asking for seconds at the party.",
        "Started a gratitude journal, writing three things I'm thankful for each day. It’s shifting my perspective!",
        "Took a dance class, learning salsa steps with a fun group. My hips don’t lie, but they need practice! The lively music and rhythmic steps had me sweating and smiling, as I partnered with others to master the sultry moves of salsa.",
        "Explored a new cycling trail through rolling hills. The wind in my hair felt like freedom!",
        "Attended a virtual astronomy lecture, learning about black holes. The universe is mind-bogglingly vast! The speaker explained complex theories with stunning visuals, leaving me in awe of the mysteries beyond our planet and eager to learn more.",
        "Tried fermenting my own pickles, watching the brine bubble. It’s a tangy science experiment!",
        "Spent the afternoon sketching portraits of my pets. Capturing their quirky expressions is so rewarding! I used charcoal to shade their fluffy fur and bright eyes, creating drawings that capture their personalities to hang in my home.",
        "Joined a local chess club, sharpening my strategy with every match. Checkmate feels so good!",
        "Took a floral arrangement class, creating a stunning bouquet with roses and eucalyptus. My table looks gorgeous! I learned to balance colors and textures, arranging fragrant blooms into a centerpiece that brightens my dining room.",
        "Went on a sunrise hot air balloon ride, floating above misty fields. The views were absolutely magical!",
        "Started learning about aromatherapy, blending essential oils for relaxation. My home smells like a spa! I mixed lavender and chamomile oils, diffusing them to create a calming atmosphere that helps me unwind after busy days.",
        "Tried my hand at woodworking, crafting a small shelf. Sanding and staining is oddly satisfying!",
        "Attended a poetry slam, hearing powerful verses from local poets. Words have such raw energy! The performers’ passion filled the room, and I clapped along, inspired to write my own poem after their moving stories and rhythms.",
        "Spent the day foraging for wild edible plants with a guide. Nature’s pantry is incredible!",
        "Tried aerial yoga, swinging in silk hammocks. It’s a playful way to stretch and strengthen! Floating through poses in the soft fabric challenged my balance, but the gentle sway made every stretch feel like a dance in the air.",
        "Explored a new art gallery, admiring bold abstract paintings. Creativity sparks so many emotions!",
        "Took a pottery wheel class, centering clay and shaping a vase. The wheel’s hum is so soothing! Muddy hands and the spinning clay drew me into a meditative flow, as I crafted a graceful vase to hold fresh flowers from my garden.",
        "Started a podcast listening marathon, diving into true crime stories. I’m hooked on the suspense!",
        "Tried my hand at leatherworking, stitching a simple wallet. The smell of leather is so rich! I carefully cut and sewed the material, adding a personal monogram to create a durable, handmade piece that’s both practical and stylish.",
        "Joined a stargazing group, spotting planets through a telescope. Jupiter’s moons blew my mind!",
        "Baked homemade sourdough bread, kneading dough and savoring the crusty loaf. Baking is love made edible! The tangy starter bubbled as I shaped the loaf, and the golden crust crackled perfectly when I sliced it for dinner.",
        "Took a virtual language class, practicing basic French phrases. Bonjour, new skills!",
        "Spent the day at a vineyard, learning about grape varieties and sipping wine. Cheers to new experiences! I strolled through rows of vines, tasted crisp whites and bold reds, and learned how soil and sun shape each glass’s flavor.",
        "Tried my hand at embroidery, stitching colorful patterns on a tote bag. Needlework is so intricate!",
        "Joined a virtual fitness challenge, logging daily workouts. Feeling stronger every day! I’m tracking runs, yoga, and strength sessions, pushing myself to hit new personal records while connecting with others in the online community.",
        "Explored a new nature reserve, spotting rare birds and wildflowers. Nature’s diversity is stunning!",
        "Took a candle-making workshop, pouring soy wax with vanilla scents. My home glows with warmth! I layered wicks and melted wax, experimenting with scents to craft candles that cast a cozy glow for my evening reading sessions.",
        "Started learning about minimalism, simplifying my possessions. Less stuff, more freedom!",
        "Tried my hand at stop-motion animation, creating a short film with clay figures. It’s tedious but so cool! I molded tiny characters, snapping hundreds of frames to bring a whimsical story to life, amazed at the magic of each small movement.",
        "Attended a virtual history lecture about ancient civilizations. The past teaches us so much!",
        "Spent the day kite flying at the park, watching my kite soar. Simple joys bring the biggest smiles! The bright kite danced in the wind, tugging the string as I ran across the field, laughing under a wide blue sky.",
        "Tried my hand at basket weaving, crafting a small reed basket. It’s a timeless skill!",
        "Joined a virtual writing group, sharing short stories and feedback. Creativity thrives in community! I read my latest draft aloud, gaining insights from fellow writers that sharpened my narrative and fueled my passion for storytelling.",
        "Took a wildlife photography class, learning to capture animals in motion. Patience pays off!",
        "Spent the day at a lavender farm, picking fresh sprigs and sipping lavender lemonade. Pure bliss! The fields glowed purple, and I filled a basket with fragrant stems, relaxing with a cool drink under the warm sun.",
        "Tried my hand at mosaics, piecing together colorful tiles. Art from broken pieces is beautiful!",
        "Started learning about permaculture, designing a sustainable garden. Earth-friendly living inspires me! I’m planning companion plantings and water-saving layouts to create a thriving, eco-conscious garden that supports local wildlife.",
        "Took a virtual improv comedy class, laughing through silly scenes. Spontaneity is so freeing!",
        "Explored a new skate park, practicing basic tricks. Falling is part of the fun! I wobbled on my board, trying ollies and laughing off tumbles, feeling the thrill of progress with every small success on the ramps.",
        "Tried my hand at soapstone carving, shaping a small sculpture. The stone’s smoothness is addictive!",
        "Joined a virtual meditation group, practicing guided visualizations. Inner peace is a journey! I followed the guide’s voice, picturing serene landscapes, and felt my worries melt away in a session that left me refreshed.",
        "Spent the day at a pumpkin patch, picking the perfect one for carving. Fall vibes are the best!",
        "Tried my hand at block printing, carving designs and stamping fabric. Each print is unique! I etched bold patterns into linoleum, inking them to create custom tea towels that add a handmade charm to my kitchen.",
        "Started learning about urban farming, growing veggies in small spaces. Fresh food, city style!",
        "Took a virtual mixology class, shaking up mocktails with flair. Cheers to creativity! I mixed tangy citrus and sweet syrups, learning garnishes and techniques to craft refreshing drinks for my next gathering.",
        "Explored a new coastal trail, collecting seashells and breathing salty air. The ocean heals!",
    ]

    current_date = datetime(2024, 1, 1)
    for sample_post in sample_posts:
        random_user = random.choice(users)
        random_hour = random.randint(0, 23)
        random_minute = random.randint(0, 59)
        random_second = random.randint(0, 59)
        post_date = current_date.replace(hour=random_hour, minute=random_minute, second=random_second)
        
        Post.objects.create(user=random_user, content=sample_post, created_at=post_date)
       
        days_increment = random.randint(2, 4)
        current_date += timedelta(days=days_increment)


def remove_data(apps, schema_editor):
    Post = apps.get_model('network', 'Post')
    Post.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_add_users'),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
