# Generated by Django 5.2 on 2025-05-06 00:01

from django.db import migrations
import random


def add_likes(apps, schema_editor):
    User = apps.get_model('network', 'User')
    Post = apps.get_model('network', 'Post')
    Like = apps.get_model('network', 'Like')
    
    all_users = list(User.objects.all())
    all_posts = list(Post.objects.all())
    
    for post in all_posts:
        post_creator = post.user
        
        # Filter out the post creator from potential likers
        potential_likers = [user for user in all_users if user != post_creator]
        
        # Randomly choose how many users will like this post (1-3)
        num_likers = min(random.randint(1, 3), len(potential_likers))
        
        # Randomly select unique users who will like this post
        chosen_likers = random.sample(potential_likers, num_likers)
        
        # Create like objects
        for liker in chosen_likers:
            Like.objects.create(user=liker, post=post)

def remove_likes(apps, schema_editor):
    Like = apps.get_model('network', 'Like')
    Like.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_add_posts'),
    ]

    operations = [
        migrations.RunPython(add_likes, reverse_code=remove_likes)
    ]
